FROM ubuntu:18.04

# Make sure apt-get is up to date and dependent packages are installed
RUN \
  apt-get update && \
  apt-get install -y automake autogen build-essential ca-certificates \
    gcc-mingw-w64 g++-mingw-w64 \
    make xz-utils cpio wget zip unzip git texinfo help2man \
    --no-install-recommends

# Fix any stock package issues
RUN ln -s /usr/include/asm-generic /usr/include/asm
ENTRYPOINT ["/bin/bash"]
